/**
 * THE CANONICAL MESSAGING TYPES.
 *
 * Generated by hand from `apps/api/src/communication/contracts/dto.ts` and
 * `events.ts` — camelCase, exactly as the API serves them. When those files
 * change, this one changes; nothing here is a client invention.
 *
 * ## Why this is a new file rather than a rewrite of `domain.ts`
 *
 * `domain.ts` describes the superseded Customer-Success CRM: `InboxRow`,
 * `Case`, `Task`, `Shift`, `Absence`, and a snake_case `Message` from an API
 * that was never built. Those types are FROZEN (see
 * `docs/recovery/PHASE-0-ADMIN-WEB-RECONCILIATION.md` §2.7) and the features
 * using them are unrouted, not deleted.
 *
 * Rewriting `domain.ts` in place would therefore have meant either breaking
 * every frozen file at once, or leaving canonical and brief-era shapes
 * interleaved in one module under the same names. Two files, each honest about
 * what it describes, is the clearer arrangement — and it makes the migration
 * legible in review: an import from here is console code, an import from
 * `domain.ts` is frozen code.
 */

export type StaffRole = 'admin' | 'coverage_admin' | 'manager' | 'super_admin'

export type ActorKind = 'contact' | 'staff' | 'teacher' | 'system'

export type ConversationType = 'direct' | 'student_group' | 'class_group' | 'official'

export type ConversationState =
  | 'open'
  | 'waiting_on_customer'
  | 'waiting_on_jawwid'
  | 'resolved'

export type MessageType = 'text' | 'image' | 'video' | 'voice' | 'file' | 'system'

export type Visibility = 'customer' | 'internal'

export type Moderation = 'published' | 'pending' | 'rejected'

export type OnBehalfMode = 'owner' | 'coverage' | 'assist' | 'escalation'

export type ReceiptState = 'sent' | 'delivered' | 'read'

/** The reactions the API accepts. Mirrors `vocab.ts` REACTION_EMOJI. */
export const REACTION_EMOJI = ['👍', '❤️', '😂', '😮', '😢', '🙏'] as const

export interface ConversationMember {
  actorId: string
  actorKind: ActorKind
  memberRole: 'parent' | 'teacher' | 'admin' | 'observer'
  isSilent: boolean
  /** Resolved by the server. Never a phone number or an e-mail. */
  displayName?: string
}

export interface Attachment {
  id: string
  kind: string
  mimeType: string
  byteSize: number
  originalName: string | null
  durationMs: number | null
  width: number | null
  height: number | null
  /** Short-lived and signed. Never a permanent storage URL. */
  url: string | null
  thumbnailUrl: string | null
}

/**
 * The quoted message above a reply.
 *
 * `available` is false when the target was deleted, is restricted to this
 * reader, or is gone — and then `excerpt` is null. The server decides this, so
 * the console renders whichever it is told and never substitutes text of its
 * own for a quote it was not given.
 */
export interface ReplyPreview {
  messageId: string
  available: boolean
  unavailableReason: 'deleted' | 'restricted' | 'missing' | null
  authorKind: ActorKind | null
  authorId: string | null
  type: MessageType | null
  excerpt: string | null
}

export interface MessageReceipt {
  actorId: string
  state: ReceiptState
  deliveredAt: string | null
  readAt: string | null
}

export interface Message {
  id: string
  conversationId: string | null
  /** Stringified: 64-bit, and JSON numbers are not safe at that width. */
  seq: string | null
  authorKind: ActorKind
  authorId: string | null
  onBehalfMode: OnBehalfMode | null
  type: MessageType
  /** Null for a message deleted for everyone: the body is never served again. */
  body: string | null
  visibility: Visibility
  moderation: Moderation
  origin: 'user' | 'automation' | 'broadcast'
  replyToMessageId: string | null
  replyPreview: ReplyPreview | null
  clientMessageId: string | null
  editedAt: string | null
  editCount: number
  /**
   * A boolean, deliberately — the source conversation is usually one this
   * reader may not access, so the API serves the fact and not the reference.
   */
  isForwarded: boolean
  deletedAt: string | null
  deletedForAll: boolean
  createdAt: string
  attachments: Attachment[]
  reactions: Array<{ actorId: string; emoji: string }>
  receipts: MessageReceipt[]
}

export interface Conversation {
  id: string
  type: ConversationType
  familyId: string | null
  learnerId: string | null
  title: string | null
  state: ConversationState
  needsReply: boolean
  lastSeq: string
  lastActivityAt: string
  archivedAt: string | null
  teacherRequiresApproval: boolean
  parentRequiresApproval: boolean
  members?: ConversationMember[]

  /** Present on the list and on the by-id read; absent elsewhere. */
  unreadCount?: number
  lastMessagePreview?: string
  lastMessageAt?: string | null
  lastMessageAuthorId?: string | null
  isPinned?: boolean
  isMuted?: boolean
  isArchivedForMe?: boolean
}

export interface MessagePage {
  messages: Message[]
  /** Non-null only when a full page came back, so its presence is "there may be more". */
  nextBefore: string | null
}

export interface MessageSearchHit {
  message: Message
  conversationId: string
  conversationType: ConversationType
  conversationTitle: string | null
}

export interface MessageSearchResult {
  hits: MessageSearchHit[]
  nextCursor: string | null
}

export interface MessageRevision {
  revision: number
  body: string | null
  replacedBy: string
  replacedAt: string
}

/**
 * The queue sections that replace the brief's four attention buckets.
 *
 * Membership is computed HERE, from fields the API already serves on the
 * conversation list, rather than from an attention engine the API does not
 * have. Each section is a plain predicate, stated once, so what an operator
 * sees in a section is exactly what its name says.
 */
export type QueueSection = 'needs_reply' | 'waiting_on_customer' | 'all'

export function sectionOf(conversation: Conversation): Exclude<QueueSection, 'all'> {
  return conversation.needsReply ? 'needs_reply' : 'waiting_on_customer'
}

/** Newest activity first — the order an operator works a queue in. */
export function byMostRecent(a: Conversation, b: Conversation): number {
  return new Date(b.lastActivityAt).getTime() - new Date(a.lastActivityAt).getTime()
}
